name: '"Configure buildx with Namespace Cloud" Action For GitHub Actions'
description: "Configure buildx to use the Namespace Cloud build cluster"

runs:
  using: node20
  main: dist/main/index.js
  post: dist/post/index.js
